name: beeline
channels:
  - conda-forge
dependencies:
  # Core interpreters
  - python=3.11
  - r-base=4.3
  # Inter-language bridge
  - rpy2
  # Scientific stack
  - numpy>=2.0
  - pandas>=2.2
  - matplotlib>=3.8
  - seaborn>=0.13
  - scikit-learn>=1.5
  - networkx
  - tqdm
  - anndata>=0.10
  - scanpy=1.11.*
  - pyyaml
  - pip
  - pip:
      - mygene==3.2.2